---
output:
  govdown::govdown_document:
    page_title: "Civil Service People Survey Results Explorer"
    css: style.css
---

<script src="static/jquery-3.3.1.min.js"></script>
<script src="static/jquery.peity.min.js"></script>

``` {js echo=FALSE}
<!-- Add custom styles-->

$('head').append('<link rel="stylesheet" href="style.css" type="text/css" />');

```


``` {r setup, include=FALSE}

library(tidyverse)

diff_postproc <- function(str, x) {
  
  fmt <- case_when(
    is.na(x) | x < 0 ~ "%s",
    x == 0 ~ "=",
    x > 0 ~ "+%s")
  
  sprintf(fmt, str)
  
}

diff_formatter <- function(x, digits = 0L, format = "f", big.mark = ",", ...) {
  
  formattable::formattable(janitor::round_half_up(as.numeric(x), digits = digits), 
                           format = format, 
                           big.mark = big.mark,
                           digits = digits, 
                           ..., 
                           postproc = "diff_postproc")
}

csps_sparkline <- function(x) {
  
  x <- paste0(as.numeric(x), collapse=",")
  
  htmltools::span(class="csps-sparkline", x)
  
}

csps_median_all <- read_csv("data/csps_median.csv")

csps_median_2019_summary <- csps_median_all %>%
  filter(year == 2019, theme == "SUMMARY") %>%
  arrange(sortorder) %>%
  pull(value) %>%
  formattable::percent(digits = 0)

names(csps_median_2019_summary) <- csps_median_all %>%
  filter(year == 2019, theme == "SUMMARY") %>%
  arrange(sortorder) %>%
  pull(measure)

csps_median_2018_summary <- csps_median_all %>%
  filter(year == 2018, theme == "SUMMARY") %>%
  arrange(sortorder) %>%
  pull(value) %>%
  formattable::percent(digits = 0)

names(csps_median_2018_summary) <- csps_median_all %>%
  filter(year == 2018, theme == "SUMMARY") %>%
  arrange(sortorder) %>%
  pull(measure)

csps_median_2019_summary_diff <- ((csps_median_2019_summary - 
                               csps_median_2018_summary) * 100) %>%
  diff_formatter()

names(csps_median_2019_summary_diff) <- names(csps_median_2019_summary)

csps_spark_dt <- csps_median_all %>% 
  filter(theme == "SUMMARY") %>%
  select(year, measure, value) %>%
  pivot_wider(names_from = measure, values_from = value) %>%
  arrange(year)

```


# Civil Service People Survey Results Explorer

This microsite provides interactive tools to explore the published results of the Civil Service People Survey results. Please note that while this site is based on published data, this is an experimental prototype and a work in progress, as such is not an official publication of the Cabinet Office and does not represent government policy. For full details and results please visit the [Civil Service People Survey Hub](https://www.gov.uk/government/collections/civil-service-people-survey-hub) on GOV.UK.

## 2019 headline results

The 2019 People Survey was the eleventh annual survey of our employees’ attitudes and
experiences of working in the Civil Service. 308,556 civil servants responded, across 106 Civil Service organisations. This is equivalent to an overall response rate for
the Civil Service of 67%, an increase of 0.2 percentage points compared to 2018.

The Employee Engagement Index has increased by one percentage point to 63%, the highest it has
ever been. Eight of the nine themes scores within the survey have also increased since 2018, with only the score for the ‘organisational objectives and purpose’ theme remaining the same. 

The headline Civil Service benchmark results are shown below, you can view the results for invidival questions on the [benchmark results page](benchmark-results.html).

:::{.govuk-grid-row .box-row}

:::{.govuk-grid-column-full .metric-box}
#### Employee engagement index
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["EES"]`</span> `r csps_sparkline(csps_spark_dt$EES)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["EES"]`</span> Oct 2018 to Oct 2019
:::

:::


:::{.govuk-grid-row .box-row}

:::{.govuk-grid-column-one-third .metric-box}
#### My work
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["MW"]`</span> `r csps_sparkline(csps_spark_dt$MW)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["MW"]`</span> Oct 2018 to Oct 2019
:::

:::{.govuk-grid-column-one-third .metric-box}
#### Organisational objectives and purpose
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["OP"]`</span> `r csps_sparkline(csps_spark_dt$OP)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["OP"]`</span> Oct 2018 to Oct 2019
:::

:::{.govuk-grid-column-one-third .metric-box}
#### My manager
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["LM"]`</span> `r csps_sparkline(csps_spark_dt$LM)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["LM"]`</span> Oct 2018 to Oct 2019
:::

:::

:::{.govuk-grid-row .box-row}


:::{.govuk-grid-column-one-third .metric-box}
#### My team
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["MT"]`</span> `r csps_sparkline(csps_spark_dt$MT)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["MT"]`</span> Oct 2018 to Oct 2019
:::

:::{.govuk-grid-column-one-third .metric-box}
#### Learning and development
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["LD"]`</span> `r csps_sparkline(csps_spark_dt$LD)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["LD"]`</span> Oct 2018 to Oct 2019
:::

:::{.govuk-grid-column-one-third .metric-box}
#### Inclusion and fair treatment
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["IF"]`</span> `r csps_sparkline(csps_spark_dt$IF)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["IF"]`</span> Oct 2018 to Oct 2019
:::

:::

:::{.govuk-grid-row .box-row}

:::{.govuk-grid-column-one-third .metric-box}
#### Resources and workload
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["RW"]`</span> `r csps_sparkline(csps_spark_dt$RW)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["RW"]`</span> Oct 2018 to Oct 2019
:::

:::{.govuk-grid-column-one-third .metric-box}
#### Pay and benefits
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["PB"]`</span> `r csps_sparkline(csps_spark_dt$PB)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["PB"]`</span> Oct 2018 to Oct 2019
:::

:::{.govuk-grid-column-one-third .metric-box}
#### Leadership and managing change
<span class="govuk-!-font-size-48 govuk-!-font-weight-bold">`r csps_median_2019_summary["LC"]`</span> `r csps_sparkline(csps_spark_dt$LC)`<br/>
<span class="govuk-!-font-size-24">`r csps_median_2019_summary_diff["LC"]`</span> Oct 2018 to Oct 2019
:::

:::

::: {.small-para}
Note: sparkline charts represent the time-series from 2009 to 2019, they show the relative change for each survey result over time.
:::


``` {js echo=FALSE}
<!-- Add jQuery post-processing -->

$.fn.peity.defaults.line = {
  delimiter: ",",
  fill: "#1d70b833",
  height: 40,
  max: null,
  min: null,
  stroke: "#1d70b8",
  strokeWidth: 2,
  width: 80
}

$(".csps-sparkline").peity("line")

```
