---
output:
  govdown::govdown_document:
    page_title: "Tab/browser title goes here"
    css: style.css
---

``` {r R_html_opts, echo=FALSE}
htmltools::tags$link(href = "style.css", rel = "stylesheet")
# htmltools::tags$script(src = "static/jquery-3.3.1.min.js")
# htmltools::tags$script(src = "static/jquery.peity.min.js")

govuk_reactable_theme <- reactable::reactableTheme(
    borderColor = "#b1b4b6",
    borderWidth = "1px",
    paginationStyle = list(
      "font-weight" = "400",
      "font-size" = "14px",
      "font-size" = "0.875rem",
      "line-height" = "1.14286",
      "margin-top" = "0",
      "margin-bottom" = "15px"),
    pageButtonStyle = list(
      "font-weight" = "700",
      "font-size" = "14px",
      "font-size" = "0.875rem",
      "line-height" = "1.14286",
      "display" = "inline-block",
      "position" = "relative",
      "margin-top" = "0",
      "margin-left" = "2px",
      "margin-right" = "2px",
      "padding" = "8px 10px 7px",
      "border" = "2px solid rgba(0, 0, 0, 0)",
      "border-radius" = "0",
      "color" = "#454a4d",
      "background-color" = "#eff0f1",
      "text-align" = "center",
      "vertical-align" = "middle",
      "cursor" = "pointer"
      ),
    pageButtonCurrentStyle = list(
      "color" = "#144e81",
      "background-color" = "#d2e2f1",
      "box-shadow" = "0 2px 0 #144e81"
      )
  )

```

``` {r setup, include=FALSE}

```

# Page title goes here

`{DT}` table with `style="jqueryui"` setting

```{r, echo=FALSE}
DT::datatable(iris, style = "jqueryui", class = "govuk-table govuk-!-font-size-16", elementId = "tbl1")
```


`{reactable}` table with custom `govuk_reactable_theme`

```{r, echo=FALSE}
reactable::reactable(
  iris,
  class = "govuk-table",
  theme = govuk_reactable_theme,
  searchable = TRUE)
```

<!-- No content -->

``` {js jquery, echo=FALSE}

$(document).ready(function(){console.log("loaded");});

govuk_DT_styling = function() {
  console.log("govuk_DT_styling");
  $(".datatables").addClass("govuk-body-s");
  $(".datatables th").addClass("govuk-table__header");
  $(".datatables td").addClass("govuk-table__cell");
  $(".datatables").addClass("govuk-!-font-size-16");
  $(".datatables label").addClass("govuk-label govuk-!-font-size-16");
  $(".datatables select").addClass("govuk-select govuk-!-font-size-16");
  $(".datatables input").addClass("govuk-input govuk-!-font-size-16");
  $(".datatables a.ui-button:not(.ui-state-disabled)").addClass("govuk-tag govuk-tag--grey govuk-!-font-size-14");
  $(".datatables a.ui-button.ui-state-disabled").addClass("govuk-tag govuk-tag--blue govuk-!-font-size-14");
  $(".datatables a.ui-button.previous.ui-state-disabled").css("display","none");
  $(".datatables a.ui-button.next.ui-state-disabled").css("display","none");
  $(".datatables table").css("border-bottom","unset");
}

$(".datatables").on('draw.dt', function(){govuk_DT_styling();});

```
